schema: ./storage/app/lighthouse-schema.graphql
include:
  - graphql/**
  - schema-directives.graphql
exclude:
  - resources/app/graphql/queries/*

extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://baander.ddev.site/graphql
      introspect: false
