schema: './storage/lighthouse-schema.graphql'
documents: '**/*.graphql'
include:
  - './schema-directives.graphql'
    #- './storage/lighthouse-schema.graphql'
    #- './resources/**/*.graphql'

extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://baander.ddev.site/graphql
      introspect: false
